import SearchHeader from "./components/Header";
import RestaurantCard from "./components/RestaurantCard";
import SearchSideBar from "./components/SearchSideBar";

export const metadata = {
  title: 'Search | OpenTable',
  description: 'Generated by create next app',
}

export default function SearchPage() {
  return (
    <>
      <SearchHeader />
      <div className="flex items-start justify-between w-2/3 py-4 m-auto">
        <SearchSideBar />
        <div className="w-5/6">
          <RestaurantCard />
        </div>
      </div>
    </>
  )
}