import RestaurantHeader from "./components/RestaurantHeader"

export const metadata = {
  title: 'Red Lobster (Bolingbrook) | OpenTable',
  description: 'Generated by create next app',
}

export default function RestaurantLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: {slug: string}
}) {
  return (
    <main>
      <RestaurantHeader name={params.slug} />
      <div className="flex items-start justify-between w-2/3 m-auto 0 -mt-11">
        {children}
      </div>
    </main>
  )
}